name: Deploy agione

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GLOBAL_ACCESS_TOKEN }}
          fetch-depth: '0'

      - name: Set up Git credentials
        run: |
          git config --global credential.helper store
          git config --global user.password ${{ secrets.GLOBAL_ACCESS_TOKEN }}
          git config --global url.https://${{ secrets.GLOBAL_ACCESS_TOKEN }}@github.com/.insteadOf https://github.com/
        shell: bash
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install Quasar CLI
        run: |
          npm cache clean --force
          npm install -g @quasar/cli

      - name: Install dependencies
        run: |
          npm install
      - name: Initialize and update submodules
        run: |
          git submodule update --init --remote
          git submodule foreach --recursive git fetch
          git submodule foreach --recursive git checkout staging
          git -C src/modules/qcrud checkout dashboard_merge_stg
          git -C src/modules/qsite checkout dashboard_merge_stg
      - name: Build Agione
        run: quasar build -m pwa
      - name: deploy angione azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{
            github.ref == 'refs/heads/master' && secrets.AZURE_DEPLOY_TOKEN_MAIN ||
            github.ref == 'refs/heads/stg' && secrets.AZURE_DEPLOY_TOKEN_STAGING ||
            github.ref == 'refs/heads/dev' && secrets.AZURE_DEPLOY_TOKEN_DEV ||
            github.ref == 'refs/heads/QA' && secrets.AZURE_DEPLOY_TOKEN_DEV_V3 ||
            github.ref == 'refs/heads/localhost' && secrets.AZURE_DEPLOY_TOKEN_LOCAL}}
          action: "upload"
          app_location: "dist/pwa" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
