name: playwright-tests

on:
  push:
    branches:
      - stg

jobs:
  test:
    name: Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Create env.js file
        run: |
          echo "const email = '${{ secrets.AGIONE_FRONTEND_TEST_USER_EMAIL }}';" > env.js
          echo "const password = '${{ secrets.AGIONE_FRONTEND_TEST_USER_PASSWORD }}';" >> env.js
          echo "module.exports = { email, password };" >> env.js
          
      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-v1

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests for setup
        run: npx playwright test --project setup
      - name: Run Playwright tests for chromium
        run: npx playwright test --project chromium
